# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: CI proccess API Backend Newus Web

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [20]
        
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: '20.x'
    - name: Run migration if present
      run: |
          cd /home/newus-api-services/htdocs/api-services.newus.id
          git pull
          npx sequelize-cli db:migrate
    
    - name : change repo
      run : cd /home/newus-api-services/htdocs/api-services.newus.id/actions-runner/_work/website-be/website-be
    - run : pm2 restart api-services.newus.id
